### ISSUE TITLE
[Language] Powershell

### ISSUE THREAD

**Issue by ulyssear** [codethesaurus/codethesaur.us#694] opened 2023-10-29 01:28 UTC
# Language you would like added

Powershell

# Information on the language

Official documentation : https://learn.microsoft.com/powershell/ 

# Disclaimer

Please can i work on this issue ?

**Comment by geekygirlsarah** [comment] 2023-10-29 16:29
This is a duplicate of #449. If you leave a comment on there I'll happily assign you!

**Closed as not planned** 2023-10-29 16:40 UTC
Labels: duplicate

**Comment by ulyssear** [comment] 2023-10-29 19:03
I have started to do the first concepts : classes #696 and controls structures which will be done soon.

**Comment by geekygirlsarah** [comment] 2023-10-30 19:22
Can you use #449 instead since this is a duplicate of that ticket?

**Comment by ulyssear** [comment] 2023-10-30 19:29
Ok ! i will add the others concepts. I think it will better to have a task list to check the advancement on this issue.
