### ISSUE TITLE
Java missing lists/collections entry

### ISSUE THREAD

**Issue by jeff303** [codethesaurus/codethesaur.us#623] opened 2022-10-21 03:29 UTC
# Language

Java (all versions)

# Additional Information

Java could use the `lists.json` file filled in, since it has support for most of the collection types included here.

**Comment by cafce25** [comment] 2022-10-21 17:34
This is just a duplicate of #286 where somebody else is assigned.

**Comment by geekygirlsarah** [comment] 2022-10-22 15:28
True. I'll go ahead and close this. 

That person requested it 14 days ago and I haven't seen a PR yet, so what I can do is shift your PR to point to 286. If they don't make a PR and the bot unassigns them in a couple of days, I'll review yours, @jeff303 .

(for now, closing this issue as a duplicate.)

**Closed as not planned by geekygirlsarah** 2022-10-22 15:28 UTC
Labels: duplicate
